name: Build apps

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build .NET Core Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets: [win-x86, win-x64, win-arm64, linux-x64, linux-arm64, osx-x64, osx-arm64]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build AzureIoT
        run: dotnet build ./AzureIoT --no-restore --configuration Release

      - name: Build WebAPI
        run: dotnet build ./WebAPI --no-restore --configuration Release

      - name: Build Receiver
        run: dotnet build ./Receiver --no-restore --configuration Release

      - name: Publish AzureIoT
        run: dotnet publish -r ${{ matrix.targets }} ./AzureIoT --configuration Release --output ./output/AzureIoT-${{ matrix.targets }} --self-contained

      - name: Publish WebAPI
        run: dotnet publish -r ${{ matrix.targets }} ./WebAPI --configuration Release --output ./output/WebAPI-${{ matrix.targets }} --self-contained

      - name: Publish Receiver
        run: dotnet publish -r ${{ matrix.targets }} ./Receiver --configuration Release --output ./output/Receiver-${{ matrix.targets }} --self-contained

      - name: Zip AzureIoT artifacts
        run: zip -r AzureIoT-${{ matrix.targets }}.zip ./output/AzureIoT-${{ matrix.targets }}

      - name: Zip WebAPI artifacts
        run: zip -r WebAPI-${{ matrix.targets }}.zip ./output/WebAPI-${{ matrix.targets }}

      - name: Zip Receiver artifacts
        run: zip -r Receiver-${{ matrix.targets }}.zip ./output/Receiver-${{ matrix.targets }}

      - name: Release builds
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ matrix.targets }}
          name: Latest build for ${{ matrix.targets }}
          files: |
            AzureIoT-${{ matrix.targets }}.zip
            WebAPI-${{ matrix.targets }}.zip
            Receiver-${{ matrix.targets }}.zip
